### PR TITLE
Ready this for publication to the Python Package Index

### PR DESCRIPTION
**Pull request by nutjob4life**
## Purpose

Makes this repository ready for publication to the [Python Package Index](https://pypi.org/) so end-users can simply `pip install` it without checking out the code, without managing dependencies, etc. All they need is a working Python.

## Proposed Changes
- Makes a new console script available: `slim`
- Removes `requirements.txt` and replaces it with `pyproject.toml` which has both the dependencies and the package metadata
- Updates the README instructions to demonstrate installation from PyPI as well as how to continue local development
- Adds support for `--version` and version tracking
- Adds a `.gitignore`
- Removes potential [Dependency Confusion Vulnerabilities](https://medium.com/@alex.birsan/dependency-confusion-4a5d60fec610)
- Comments-out `tabulate` dependency; it doesn't appear to be used
- Removes `argparse` dependency; it's part of the standard library

## Issues

N/A.

## Testing

```console
bash-3.2$ python3 -m venv .venv
bash-3.2$ . .venv/bin/activate
(.venv) bash-3.2$ pip install --quiet --editable .

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: pip install --upgrade pip
(.venv) bash-3.2$ which slim
/private/tmp/slim-cli/.venv/bin/slim
(.venv) bash-3.2$ slim --version
0.0.0
``` 

## Notes

This doesn't actually publish SLIM CLI to PyPI. I'll leave it to the repository owners to do that so they can grab the name before someone else does (including me).

To do so (assuming your `~/.pypirc` is set up):
```
bash-3.2$ python3 -m venv .venv
bash-3.2$ . .venv/bin/activate
(.venv) bash-3.2$ pip install --quiet build wheel twine

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: pip install --upgrade pip
(.venv) bash-3.2$ python3 -m build .
…
(.venv) bash-3.2$ twine upload dist/*
…
```

### CODE REVIEW

**Comment by yunks128** [comment]
@nutjob4life Thank you for your contribution! 
It's published: 
https://pypi.org/project/slim-cli/

**Comment by nutjob4life** [comment]
@yunks128 awesome! And thanks for moving so quickly on this! 🎉

**Comment by yunks128** [comment]
Thank you @nutjob4life ! I invite you and @riverma as collaborators! I appreciate your help!

**Comment by riverma** [comment]
@nutjob4life - just tested out your GREAT improvements to the organization, user experience, and setup process for slim-cli. Absolutely wonderful. Thank you so much for your most excellent contributions! The branch is even deliciously named `cheeseshop`! 

I love how I can run the tool as simply now like:
```
slim list
```

Brilliant contribution and thank you!

**Comment by nutjob4life** [comment]
Aww, I appreciate that (and for noticing my branch name 😉) but seriously @yunks128 deserves the lion's share of the credit! Thank _you_ KS! 🎉 🎸

**Pull request merged**
